In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data types of the variables list_ and array_list. list_ is a Python list, and array_list is a NumPy array. You can check their data types using the type() function. Here's the code to print the data types of both variables:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types
print("Data type of list_: ", type(list_))
print("Data type of array_list: ", type(array_list))


Data type of list_:  <class 'list'>
Data type of array_list:  <class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [ ]:
To print the data type of each and every element of both the list_ and array_list variables, you can use a loop to iterate through the elements and apply the type() function to each element. Here's the code to do that:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
In this code:

We use a loop to iterate through each element in list_ and array_list.

Inside the loop, we apply the type() function to each element to print its data type.

When you run this code, it will display the data type of each element in both list_ and array_list.






In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [ ]:
If you create the array_list with the specified data type (dtype=int), it will force all elements in the array to be of integer type. Here's the code with the updated array_list

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print the data type of the array_list itself
print("Data type of array_list: ", type(array_list))

# Print the data type of each element in array_list
print("Data types of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of array_list:  <class 'numpy.ndarray'>
Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
In this code, we use dtype=int when creating array_list. This will explicitly convert the elements from strings to integers, and the array_list will contain integer data types.

When you run this code, you will see that the data type of array_list is still numpy.ndarray, but the data type of each element in array_list will be int

In [ ]:
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [ ]:
In the code you provided, where num_list is a list containing lists, and num_array is a NumPy array created from num_list, there will be a difference in the data types of the elements present in num_list and num_array. Specifically, the elements in num_list will be of the list data type, while the elements in num_array will be of the numpy.ndarray data type.

Here's the code to print the data types of each and every element present in both num_list and num_array

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Print the data types of elements in num_list
print("Data types of elements in num_list:")
for sublist in num_list:
    for element in sublist:
        print(type(element))

# Print the data types of elements in num_array
print("\nData types of elements in num_array:")
for element in num_array.flat:
    print(type(element))


Data types of elements in num_list:
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

Data types of elements in num_array:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
In this code:

We use nested loops to iterate through each element in num_list and num_array.

Inside the loops, we apply the type() function to each element to print its data type.

When you run this code, it will display the data types of each element in both num_list and num_array. You will observe that the elements in num_list are of type int because they are standard Python lists, while the elements in num_array are of type numpy.int64 because they are part of a NumPy array.






In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [ ]:
You can find the shape and size of the NumPy array num_array using the .shape and .size attributes, respectively. Here's the code to do that:

In [5]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape

# Find the size of num_array
size = num_array.size

# Print the shape and size
print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
In this code:

We use the .shape attribute to find the shape (dimensions) of the NumPy array num_array.

We use the .size attribute to find the size (total number of elements) of the NumPy array num_array.

When you run this code, it will print the shape and size of the num_array

In [ ]:
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [ ]:
If you want to create a NumPy array with a specific size (9) and shape (3x3), you can use the numpy.zeros() function or numpy.empty() function to initialize an array with zeros or empty values, respectively, and then reshape it to the desired shape. Here's how you can do it:

Using numpy.zeros():

In [6]:
import numpy as np

# Create an array of zeros with size 9
zero_array = np.zeros(9)

# Reshape the array to shape (3, 3)
num_array = zero_array.reshape(3, 3)

# Print the resulting array
print("NumPy array with shape (3, 3):")
print(num_array)


NumPy array with shape (3, 3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Using numpy.empty():

In [7]:
import numpy as np

# Create an array of empty values with size 9
empty_array = np.empty(9)

# Reshape the array to shape (3, 3)
num_array = empty_array.reshape(3, 3)

# Print the resulting array
print("NumPy array with shape (3, 3):")
print(num_array)


NumPy array with shape (3, 3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
